[project]
name = "stt-hk"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ctranslate2==4.6.3",
    "faster-whisper>=1.2.1",
    "numpy>=2.0",
    "soundfile>=0.12",
    "librosa>=0.10",
    "sounddevice==0.5.5",
]

[tool.uv.sources]
llmpop = { path = "../llmpop", editable = true }

[project.optional-dependencies]
llm = ["llmpop"]
